[db]
db = ""
address = "srvpro3.db"
user = ""
port = ""
password = ""

[redis]
address = ""
port = ""
password = ""
db = ""

[http_api]
port = 8080
room = true
history = true

[http_api.user]
user = { password = "", permissions = 3 }

[server]
reconnect_timeout = 180
side_timeout = 180
bo = 1
lflist = -1
#ot 0=OCG-ONLY, 1=TCG-ONLY, 2=SC-ONLY, 3=CUSTOM-ONLY, 4=NO-UNIQUE, 5=ALL
ot = 5
shuffle = true
master_rule = 5
draw_count = 1
start_hand = 5
time_limit = 180
start_lp = 8000

[server.tcp]
port = 7911
[server.udp]
port = 7913
[server.ws]
port = 7912

[cards]
expansions = ["ygopro"]
ypk = true
lflist = ""

[cards.excode]
8512558 = [0x8f, 0x54, 0x59, 0x82, 0x13a]
55088578 = [0x8f, 0x54, 0x59, 0x82, 0x13a]