[package]
name = "srvpro3-cards"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio.workspace = true
log.workspace = true
anyhow.workspace = true
ygopro_cdb_reader.workspace = true
zip.workspace = true
walkdir.workspace = true
regex.workspace = true
lazy_static.workspace = true
indexmap.workspace = true
parking_lot.workspace = true

srvpro3-log.workspace = true
srvpro3-config.workspace = true