[package]
name = "srvpro3-database"
version = "0.1.0"
edition = "2024"

[dependencies]
sea-orm.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
anyhow.workspace = true
parking_lot.workspace = true
tokio.workspace = true
log.workspace = true
redis.workspace = true

srvpro3-deck.workspace = true
srvpro3-log.workspace = true
srvpro3-config.workspace = true
